//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetroTrackSoapClient
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservices.retrotracksoapjava.juanmasierragarcia.eu/", ConfigurationName="RetroTrackSoapClient.IUserManagementWS")]
    public interface IUserManagementWS
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.retrotracksoapjava.juanmasierragarcia.eu/IUserManagementWS/log" +
            "inRequest", ReplyAction="http://webservices.retrotracksoapjava.juanmasierragarcia.eu/IUserManagementWS/log" +
            "inResponse")]
        System.Threading.Tasks.Task<RetroTrackSoapClient.loginResponse> loginAsync(RetroTrackSoapClient.loginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.retrotracksoapjava.juanmasierragarcia.eu/IUserManagementWS/reg" +
            "isterUserRequest", ReplyAction="http://webservices.retrotracksoapjava.juanmasierragarcia.eu/IUserManagementWS/reg" +
            "isterUserResponse")]
        System.Threading.Tasks.Task<RetroTrackSoapClient.registerUserResponse> registerUserAsync(RetroTrackSoapClient.registerUserRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="login", Namespace="http://webservices.retrotracksoapjava.juanmasierragarcia.eu/", Order=0)]
        public RetroTrackSoapClient.loginRequestBody Body;
        
        public loginRequest()
        {
        }
        
        public loginRequest(RetroTrackSoapClient.loginRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class loginRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        public loginRequestBody()
        {
        }
        
        public loginRequestBody(string arg0, string arg1)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="loginResponse", Namespace="http://webservices.retrotracksoapjava.juanmasierragarcia.eu/", Order=0)]
        public RetroTrackSoapClient.loginResponseBody Body;
        
        public loginResponse()
        {
        }
        
        public loginResponse(RetroTrackSoapClient.loginResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class loginResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public loginResponseBody()
        {
        }
        
        public loginResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registerUserRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registerUser", Namespace="http://webservices.retrotracksoapjava.juanmasierragarcia.eu/", Order=0)]
        public RetroTrackSoapClient.registerUserRequestBody Body;
        
        public registerUserRequest()
        {
        }
        
        public registerUserRequest(RetroTrackSoapClient.registerUserRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class registerUserRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        public registerUserRequestBody()
        {
        }
        
        public registerUserRequestBody(string arg0, string arg1)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registerUserResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registerUserResponse", Namespace="http://webservices.retrotracksoapjava.juanmasierragarcia.eu/", Order=0)]
        public RetroTrackSoapClient.registerUserResponseBody Body;
        
        public registerUserResponse()
        {
        }
        
        public registerUserResponse(RetroTrackSoapClient.registerUserResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class registerUserResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public registerUserResponseBody()
        {
        }
        
        public registerUserResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IUserManagementWSChannel : RetroTrackSoapClient.IUserManagementWS, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class UserManagementWSClient : System.ServiceModel.ClientBase<RetroTrackSoapClient.IUserManagementWS>, RetroTrackSoapClient.IUserManagementWS
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public UserManagementWSClient() : 
                base(UserManagementWSClient.GetDefaultBinding(), UserManagementWSClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.UserManagementWSPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UserManagementWSClient(EndpointConfiguration endpointConfiguration) : 
                base(UserManagementWSClient.GetBindingForEndpoint(endpointConfiguration), UserManagementWSClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UserManagementWSClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(UserManagementWSClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UserManagementWSClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(UserManagementWSClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UserManagementWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RetroTrackSoapClient.loginResponse> RetroTrackSoapClient.IUserManagementWS.loginAsync(RetroTrackSoapClient.loginRequest request)
        {
            return base.Channel.loginAsync(request);
        }
        
        public System.Threading.Tasks.Task<RetroTrackSoapClient.loginResponse> loginAsync(string arg0, string arg1)
        {
            RetroTrackSoapClient.loginRequest inValue = new RetroTrackSoapClient.loginRequest();
            inValue.Body = new RetroTrackSoapClient.loginRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            return ((RetroTrackSoapClient.IUserManagementWS)(this)).loginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RetroTrackSoapClient.registerUserResponse> RetroTrackSoapClient.IUserManagementWS.registerUserAsync(RetroTrackSoapClient.registerUserRequest request)
        {
            return base.Channel.registerUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<RetroTrackSoapClient.registerUserResponse> registerUserAsync(string arg0, string arg1)
        {
            RetroTrackSoapClient.registerUserRequest inValue = new RetroTrackSoapClient.registerUserRequest();
            inValue.Body = new RetroTrackSoapClient.registerUserRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            return ((RetroTrackSoapClient.IUserManagementWS)(this)).registerUserAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.UserManagementWSPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding(System.ServiceModel.BasicHttpSecurityMode.Transport);
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.UserManagementWSPort))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:8095/soap/api/user");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return UserManagementWSClient.GetBindingForEndpoint(EndpointConfiguration.UserManagementWSPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return UserManagementWSClient.GetEndpointAddress(EndpointConfiguration.UserManagementWSPort);
        }
        
        public enum EndpointConfiguration
        {
            
            UserManagementWSPort,
        }
    }
}
